nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/nwmac/dynamic-content/gh-pages/extensions/dynamic-content/1.0.2
  compressedEndpoint: >-
    https://raw.githubusercontent.com/nwmac/dynamic-content/gh-pages/extensions/dynamic-content/1.0.2.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= v2.10.0"
    catalog.cattle.io/display-name: Test Dynamic Content
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
